export default [
    "onclickoutside",
    "onpointermove",
    "onclick",
    "onpointerenter",
    "onpointerleave",
    "onglobalkeydown",
    "onglobalkeyup",
    "onkeydown",
    "onkeyup",
    "onwheel",
    "onpointerup",
    "onpointerdown",
    "onchange",
    "oninput",
];